[tool.poetry]
name = "rpn_calc"
version = "0.6.0"
description = "Simple RPN Calculator in Python with a Sly lexer"
authors = ["Tammy Cravit <tammymakesthings@gmail.com>"]
license = "MIT"
classifiers=[
    'Development Status :: 3 - Alpha',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.8',
    'Topic :: Math :: Calculators',
]

[tool.poetry.dependencies]
python = "^3.8"
sly = "*"
fire = "^0.4.0"
pyyaml = "*"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
nose = "^1.3.7"
ptipython = "^1.0.1"
mypy = "^0.910"
black = "^21.10b0"
pycodestyle = "^2.8.0"
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rA -x --new-first"
console_output_style = "count"
testpaths = "tests"
enable_assertion_pass_hook = true
